/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'HTC' at '15.06.2017 22:34' with Gradle 2.9
 *
 * @author HTC, @date 15.06.2017 22:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
