import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'HTC' at '15.06.2017 22:34' with Gradle 2.9
 *
 * @author HTC, @date 15.06.2017 22:34
 */
public class LibraryTest {
    @Test 
    public void test() {
    	FakeUser f = new FakeUser(0,0,1,0,0,0);

    	OutputColleting out = new OutputColleting();
        Ms.main(null,out,f);
        ArrayList<String> o = out.outputs;
        assertEquals("Verkackt!", o.get(o.size()-1));
    }
    @Test
    public void test2() {
    	FakeUser f = new FakeUser(9,9,6,9,9,9);
    	OutputColleting out = new OutputColleting();
        Ms.main(null,out,f);
        ArrayList<String> o = out.outputs;
        
        assertEquals("Verkackt!", o.get(o.size()-1));
    }
    @Test
    public void test3() {
    	FakeUser f = new FakeUser(9,0,9,9,2,9,9,0);
    	OutputColleting out = new OutputColleting();
        Ms.main(null,out,f);
        ArrayList<String> o = out.outputs;
        
        assertEquals("Verkackt!", o.get(o.size()-1));
    }
    @Test
    public void test4(){
    	FakeUser f = new FakeUser(1,1,12,12,323,34,54,5,-1,-1,-1,-4,2,1,2,2,2,2,22,-2,0,0,00,0,1,1,1);
    	OutputColleting out = new OutputColleting();
    	Ms.main(null,out,f);
    	ArrayList<String> o = out.outputs;
    	
    	assertEquals("Verkackt!", o.get(o.size()-1));
    }
}
